//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simple_Bot.ocr {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ocr.webtropy.com/", ConfigurationName="ocr.ocrSoap")]
    public interface ocrSoap {
        
        // CODEGEN: Generating message contract since element name username from namespace http://ocr.webtropy.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ocr.webtropy.com/Analyze", ReplyAction="*")]
        Simple_Bot.ocr.AnalyzeResponse Analyze(Simple_Bot.ocr.AnalyzeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AnalyzeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Analyze", Namespace="http://ocr.webtropy.com/", Order=0)]
        public Simple_Bot.ocr.AnalyzeRequestBody Body;
        
        public AnalyzeRequest() {
        }
        
        public AnalyzeRequest(Simple_Bot.ocr.AnalyzeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ocr.webtropy.com/")]
    public partial class AnalyzeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] image;
        
        public AnalyzeRequestBody() {
        }
        
        public AnalyzeRequestBody(string username, byte[] image) {
            this.username = username;
            this.image = image;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AnalyzeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AnalyzeResponse", Namespace="http://ocr.webtropy.com/", Order=0)]
        public Simple_Bot.ocr.AnalyzeResponseBody Body;
        
        public AnalyzeResponse() {
        }
        
        public AnalyzeResponse(Simple_Bot.ocr.AnalyzeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ocr.webtropy.com/")]
    public partial class AnalyzeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AnalyzeResult;
        
        public AnalyzeResponseBody() {
        }
        
        public AnalyzeResponseBody(string AnalyzeResult) {
            this.AnalyzeResult = AnalyzeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ocrSoapChannel : Simple_Bot.ocr.ocrSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ocrSoapClient : System.ServiceModel.ClientBase<Simple_Bot.ocr.ocrSoap>, Simple_Bot.ocr.ocrSoap {
        
        public ocrSoapClient() {
        }
        
        public ocrSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ocrSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ocrSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ocrSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Simple_Bot.ocr.AnalyzeResponse Simple_Bot.ocr.ocrSoap.Analyze(Simple_Bot.ocr.AnalyzeRequest request) {
            return base.Channel.Analyze(request);
        }
        
        public string Analyze(string username, byte[] image) {
            Simple_Bot.ocr.AnalyzeRequest inValue = new Simple_Bot.ocr.AnalyzeRequest();
            inValue.Body = new Simple_Bot.ocr.AnalyzeRequestBody();
            inValue.Body.username = username;
            inValue.Body.image = image;
            Simple_Bot.ocr.AnalyzeResponse retVal = ((Simple_Bot.ocr.ocrSoap)(this)).Analyze(inValue);
            return retVal.Body.AnalyzeResult;
        }
    }
}
